# Generated by Django 6.0.1 on 2026-02-03 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long URL', max_length=2048)),
                ('short_code', models.CharField(db_index=True, help_text='Unique short code for the URL', max_length=10, unique=True)),
                ('custom_code', models.BooleanField(default=False, help_text='Whether this is a custom short code')),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of times this URL has been accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this short URL expires (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this URL is active')),
                ('description', models.CharField(blank=True, help_text='Optional description for this URL', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='URLClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referer', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shortenedurl')),
            ],
            options={
                'verbose_name': 'URL Click',
                'verbose_name_plural': 'URL Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['short_code'], name='shortener_s_short_c_f1ca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['user', '-created_at'], name='shortener_s_user_id_ef3a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='urlclick',
            index=models.Index(fields=['url', '-clicked_at'], name='shortener_u_url_id_1b818a_idx'),
        ),
    ]
