# Generated by Django 6.0.1 on 2026-02-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(db_index=True, help_text='Unique short code for the URL', max_length=30, unique=True),
        ),
    ]
